/**
 * !!! DO NOT EDIT THIS FILE !!!
 */

export const GAME_OF_THE_CENTURY = `
[Event "Third Rosenwald Trophy"]
[Site "New York, NY USA"]
[Date "1956.10.17"]
[EventDate "1956.10.07"]
[Round "8"]
[Result "0-1"]
[White "Donald Byrne"]
[Black "Robert James Fischer"]
[ECO "D92"]
[WhiteElo "?"]
[BlackElo "?"]
[PlyCount "82"]

1. Nf3 Nf6 2. c4 g6 3. Nc3 Bg7 4. d4 O-O 5. Bf4 d5 6. Qb3 dxc4 7. Qxc4 c6 8. e4 Nbd7 9. Rd1 Nb6 10. Qc5 Bg4 11. Bg5 Na4 12. Qa3 Nxc3 13. bxc3 Nxe4 14. Bxe7 Qb6 15. Bc4 Nxc3 16. Bc5 Rfe8+ 17. Kf1 Be6 18. Bxb6 Bxc4+ 19. Kg1 Ne2+ 20. Kf1 Nxd4+ 21. Kg1 Ne2+ 22. Kf1 Nc3+ 23. Kg1 axb6 24. Qb4 Ra4 25. Qxb6 Nxd1 26. h3 Rxa2 27. Kh2 Nxf2 28. Re1 Rxe1 29. Qd8+ Bf8 30. Nxe1 Bd5 31. Nf3 Ne4 32. Qb8 b5 33. h4 h5 34. Ne5 Kg7 35. Kg1 Bc5+ 36. Kf1 Ng3+ 37. Ke1 Bb4+ 38. Kd1 Bb3+ 39. Kc1 Ne2+ 40. Kb1 Nc3+ 41. Kc1 Rc2# 0-1
`;

export const MAGNUS_HANS = `
[Event "Sinquefield Cup 2022"]
[Site "Chess.com"]
[Date "2022.09.04"]
[Round "03"]
[White "Carlsen, Magnus"]
[Black "Niemann, Hans Moke"]
[Result "0-1"]
[WhiteElo "2861"]
[BlackElo "2688"]
[TimeControl "5400+30"]

1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. g3 O-O 5. Bg2 d5 6. a3 Bxc3+ 7. bxc3 dxc4 8.
Nf3 c5 9. O-O cxd4 10. Qxd4 Nc6 11. Qxc4 e5 12. Bg5 h6 13. Rfd1 Be6 14. Rxd8
Bxc4 15. Rxa8 Rxa8 16. Bxf6 gxf6 17. Kf1 Rd8 18. Ke1 Na5 19. Rd1 Rc8 20. Nd2 Be6
21. c4 Bxc4 22. Nxc4 Rxc4 23. Rd8+ Kg7 24. Bd5 Rc7 25. Ra8 a6 26. Rb8 f5 27. Re8
e4 28. g4 Rc5 29. Ba2 Nc4 30. a4 Nd6 31. Re7 fxg4 32. Rd7 e3 33. fxe3 Ne4 34.
Kf1 Rc1+ 35. Kg2 Rc2 36. Bxf7 Rxe2+ 37. Kg1 Re1+ 38. Kg2 Re2+ 39. Kg1 Kf6 40.
Bd5 Rd2 41. Rf7+ Kg6 42. Rd7 Ng5 43. Bf7+ Kf5 44. Rxd2 Nf3+ 45. Kg2 Nxd2 46. a5
Ke5 47. Kg3 Nf1+ 48. Kf2 Nxh2 49. e4 Kxe4 50. Be6 Kf4 51. Bc8 Nf3 52. Bxb7 Ne5
53. Bxa6 Nc6 54. Bb7 Nxa5 55. Bd5 h5 56. Bf7 h4 57. Bd5 Ke5 0-1
`;

export const BONGCLOUD_DRAW = `
[Event "2021-magnus-carlsen-invitational-prelims"]
[Site ""]
[Date "2021.03.15"]
[Round "?"]
[White "Magnus Carlsen"]
[Black "Hikaru Nakamura"]
[Result "1/2-1/2"]

1. e4 e5 2. Ke2 Ke7 3. Ke1 Ke8 4. Ke2 Ke7 5. Ke1 Ke8 6. Ke2 Ke7 1/2-1/2
`;

export const UNEVEN_MOVES = `
[White "Foo"]
[Black "Bar"]
[Result "1/2-1/2"]
[Date "2024.01.01"]

1. e4 e5 2. Nf3 1/2-1/2
`;
