/**
 * Regional Championship 2024 - Skill 17 - Web Technologies
 * Frontend
 *
 * This is the main JS file connecting everything together.
 *
 * !!! DO NOT EDIT THIS FILE !!!
 */

import { STARTING_POSITION, move } from './position.js';
import {
    clearPieces,
    createBoard,
    renderGameInfo,
    renderPieces,
    selectGame,
} from './ui.js';
import { readGameFromPGN } from './util.js';

// initialize position and board
let position = STARTING_POSITION;
createBoard();
renderPieces(position);

/** @type {HTMLDialogElement} */
const dialog = document.querySelector('#select-game-dialog');
dialog.showModal();

// select game
selectGame().then((pgn) => {
    const game = readGameFromPGN(pgn);
    renderGameInfo(game);

    // do the moves
    game.moves.forEach((m) => {
        position = move(m, position);
        clearPieces();
        renderPieces(position);
    });
});
